Ruby on Rails capstone project - Budget app
chudisoft/budget-tracker pull request #1
Opened 2024-02-05 07:19 UTC by chudisoft

Project requirements

-  Set up the repository and tools.
-  Create the models according to the ERD diagram. Don't forget about validations and tests.
-  Implement the authentication and authorization.
-  Create the page to add a category.
-  Create the home page.
-  Create the page to add a transaction.
-  Create the transactions page.
-  Make sure your app is tested adequately.
-  Deploy the project, and test for final details.
   https://budget-manager1.onrender.com/
-  Record a video for your project.
    https://drive.google.com/file/d/1V8ybN1ztHb2e9PIVLubO7Ry4Y_xjNL7I/view?usp=sharing
-  Create a good README and PR description.

ERD diagram
![image](https://github.com/chudisoft/budget_manager/assets/119929069/353f6ee5-1654-4d82-9416-735e59c9275a)

2024-02-05 08:03 UTC, Ibizugbe requested changes
Hi @chudisoft 👋🏼👋🏼👋🏼, 

![request change](https://github.com/chudisoft/budget-tracker/assets/64643995/b4bda86c-3328-478e-9ccf-f9fa9ad0aad4)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] Input validations are implemented👍🏼.
- [x] Nice job with the "recent" and "oldest" sorting feature👍🏼.
- [x] Tests are written and they are passing👍🏼.
- [x] Nice job with the delete and edit feature for each group and transaction👍🏼.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] For your PR description, I suggest you always outline the features you have implemented in the branch, instead of the requirements of the project😉.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-05 08:03 UTC, Ibizugbe commented on Readme.md
> +```
Nice job so far👍🏼. As a requirement, kindly ensure you talk about a piece of code/feature you've implemented that you're proud of as this also makes your presentation more engaging👍🏼.

<img width="947" alt="image" src="https://github.com/chudisoft/budget-tracker/assets/64643995/90e1f7bc-b02d-460b-8085-092092176a49">

2024-02-05 08:03 UTC, Ibizugbe commented on Readme.md
> +```
Nice job deploying your application👍🏼. For an improved user experience, kindly ensure every part of the application works fine on the deployed version. currently, the signup feature doesn't work properly. please do well to fix that👍🏼.

<img width="922" alt="image" src="https://github.com/chudisoft/budget-tracker/assets/64643995/a9182259-4cd2-46f0-9028-a140c9e3af00">

2024-02-05 08:03 UTC, Ibizugbe commented on app/views/devise/sessions/new.html.erb
> +    </div>
Nice job so far👍🏼. Let's ensure the login/signup buttons match the [design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)😉.

yours 
<img width="432" alt="image" src="https://github.com/chudisoft/budget-tracker/assets/64643995/8ace34dc-643a-4018-8c51-68a43bdac19e">


design
<img width="282" alt="Screenshot 2024-02-05 at 08 49 56" src="https://github.com/chudisoft/budget-tracker/assets/64643995/8ef74f6f-6403-4039-8d47-01be126e1c3e">

please take note of the space left and right of the login button😉.

2024-02-05 08:03 UTC, Ibizugbe commented on app/views/entities/index.html.erb
> +  </div>
kindly do well to also stick to the design here, Kindly implement your `new entity/group` buttons to match the given design😉. take not of the border lines, the padding and margin.

yours
<img width="524" alt="image" src="https://github.com/chudisoft/budget-tracker/assets/64643995/8817e097-2b5a-4649-a263-d99963221ce1">

design
<img width="329" alt="image" src="https://github.com/chudisoft/budget-tracker/assets/64643995/469eae79-efc9-4860-b0df-3b2aac2445d9">

2024-02-10 07:40 UTC, prolajumokeoni approved these changes
Hi @chudisoft 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Deployed link works properly ✅ 
 - Update video presentation 👏🏿 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It would be nice to reorder your transactions( entities) by the most recent,  from the requirements the list of transactions is presented ordered by the most recent, this will be  a nice to have feature as you have implemented something like this for your categories(groups) 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-10 07:42 UTC, merged